name: Publish version

on:
  release:
    types:
      - published

jobs:

  # 非正式版执行时，不发布到商店
  cd:
    uses: zsjy/reusable-workflows/.github/workflows/theme-cd.yaml@v3
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      app-id: app-HrMpM
      skip-appstore-release: ${{ (github.event.release.prerelease || contains(github.event.release.tag_name, 'beta')) }}
      pnpm-version: 10
      node-version: 22

  # 若cd任务未执行、发布的版本是预览版、发布的标签名含有'beta'字样，则此任务也不执行
  npm-publish:
    permissions:
      contents: read    # 读取仓库代码
    name: Npm Publish
    needs: cd
    if: |
      !github.event.release.prerelease && 
      !contains(github.event.release.tag_name, 'beta')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      # 编译资源文件，用于上传到npm
      - name: Build
        run: npm run build-res --tag=${{ github.event.release.tag_name }}

      - name: npm publish
        run: npm publish --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
